99Cats/ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :cats
end

99Cats/ninety_nine_cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

99Cats/ninety_nine_cats/app/models/cat.rb
require 'action_view'

class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper
    validates :color, inclusion: { in: ['black', 'white', 'grey', 'brown'] }
    validates :sex, inclusion: { in: ['M', 'F'] }
    validates :birth_date, :color, :name, :sex, :description, presence: true

    COLORS = ['black', 'white', 'grey', 'brown']
    
    def age
        time_ago_in_words(self.birth_date)
    end
end

99Cats/ninety_nine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

99Cats/ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

    def index
        @cats = Cat.all 
        render :index
    end

    def show
        @cat = Cat.find_by(id: params[:id])
        if @cat
            render :show    
        else
            redirect_to cats_url
        end 
    end

    def new
        @cat = Cat.new
        render :new
    end

    def create
        
    end

    private

    
end

99Cats/ninety_nine_cats/app/helpers/application_helper.rb
module ApplicationHelper
end

99Cats/ninety_nine_cats/app/views/cats/index.html.erb
<ul>
<% @cats.each do |cat|%>
<li>
    <a href= "<%= cat_url(cat.id) %>">
        <%= cat.name %>
    </a>
</li>
<%end%>
</ul>

99Cats/ninety_nine_cats/app/views/cats/new.html.erb
<form action= "<% cats_url %>%" method="POST">
    <label for="name">Name</label>
    <input id="name" type="text" name="cat[name]" value="<% @cat.name %>">
    <br>

    <label for="sex">Sex</label>
    <input id="M" type="radio" name="cat[sex]" value="M" <%= "checked" if @cat.sex == "M" %>>
    <label for="M">M</label>

    <input id="F" type="radio" name="cat[sex]" value="F" <%= "checked" if @cat.sex == "F" %>>
    <label for="F">F</label>
    <br>

    <label for="color">
    <select id="color" name="cat[color]">
        <option disabled selected>SELECT A COLOR</option>
        <% Cat::COLORS.each do |color| %>
            <option value="<%= color %>"><%= color%></option>
        <% end %>
    </select>
    <br>
    
    <input type="submit" value="Create cat!">
</form>

99Cats/ninety_nine_cats/app/views/cats/show.html.erb
<table>
    <thead>
        <tr>
            <th colspan="2"><%= @cat.name %></th>
        </tr>
    </thead>
    <tbody>
    <% @cat.attributes.each do |key, val| %>
        <%unless (key == "created_at" || key == "updated_at")%>
            <tr>
                <td><%=key%></td>
                <td><%=val%></td>
            </tr>
        <% end %>
    <% end %>
        <tr>
            <td>age</td>
            <td><%= @cat.age %></td>
        </tr> 
    </tbody>
</table>

99Cats/ninety_nine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>